independent lib

diff --git a/config b/config
--- a/config
+++ b/config
@@ -1,18 +1,18 @@
-if test -n "$ngx_module_link"; then
-    if test -n "$NDK_SRCS"; then
-        echo "found ngx_devel_kit for ngx_iconv; looks good."
-    else
-        echo "error: ngx_devel_kit is required to build ngx_iconv; please put it before ngx_iconv." 1>&2
-        exit 1
-    fi
-else
-    if echo $HTTP_MODULES | grep " ndk_http_module" > /dev/null; then
-        echo "found ngx_devel_kit for ngx_iconv; looks good."
-    else
-        echo "error: ngx_devel_kit is required to build ngx_iconv; please put it before ngx_iconv." 1>&2
-        exit 1
-    fi
-fi
+#if test -n "$ngx_module_link"; then
+#    if test -n "$NDK_SRCS"; then
+#        echo "found ngx_devel_kit for ngx_iconv; looks good."
+#    else
+#        echo "error: ngx_devel_kit is required to build ngx_iconv; please put it before ngx_iconv." 1>&2
+#        exit 1
+#    fi
+#else
+#    if echo $HTTP_MODULES | grep " ndk_http_module" > /dev/null; then
+#        echo "found ngx_devel_kit for ngx_iconv; looks good."
+#    else
+#        echo "error: ngx_devel_kit is required to build ngx_iconv; please put it before ngx_iconv." 1>&2
+#        exit 1
+#    fi
+#fi
 
 ngx_feature_name=
 ngx_feature_run=no
@@ -95,8 +95,14 @@ fi
 
 ngx_addon_name=ngx_http_iconv_module
 
-HTTP_ICONV_DEPS="$ngx_addon_dir/src/ddebug.h"
-HTTP_ICONV_SRCS="$ngx_addon_dir/src/ngx_http_iconv_module.c"
+HTTP_ICONV_DEPS="                                                           \
+                    $ngx_addon_dir/src/ddebug.h                             \
+                    $ngx_addon_dir/src/ndk.h                                \
+                "
+HTTP_ICONV_SRCS="                                                           \
+                    $ngx_addon_dir/src/ngx_http_iconv_module.c              \
+                    $ngx_addon_dir/src/ndk.c                                \
+                "
 
 if test -n "$ngx_module_link"; then
     ngx_module_type=HTTP_AUX_FILTER
